export const categoryIcon = [
  { name: "Detektive" },
  { name: "Drama" },
  { name: "Fantastika" },
  { name: "Fantaziya" },
  { name: "Harbiy" },
  { name: "Jangari" },
  { name: "Komediya" },
  { name: "Kriminal" },
  { name: "Multfilmlar" },
  { name: "Sarguzasht" },
  { name: "Tarixiy" },
  { name: "Tarixiy" },
  { name: "Tarixiy" },
  { name: "Tarixiy" },
  { name: "Tarixiy" },
];
